TMS-165: Support complex elasticsearch json queries
ZeitOnline/zeit.content.cp pull request #32
Opened 2018-02-21 18:47 UTC by cutoffthetop

2018-02-26 09:42 UTC, tomster requested changes
Looks very clean but i would like to request the addition of at least some docstrings to the `elasticsearch_raw_query` property that hints at the fact that the query can be a nested dict.

and perhaps a test that triggers the `Invalid JSON` exception?

2018-02-26 10:31 UTC, wosc requested changes
An sich prima straightfowrard :+1: , die Fehlerbehandlung braucht aber noch etwas Zuwendung. :)

2018-02-26 10:31 UTC, wosc commented on src/zeit/content/cp/area.py
> +        try:
Das müssen wir als `@zope.interface.invariant` aufschreiben, damit es im UI sinnvoll angezeigt werden kann. Und ich denke, wir sollten mind. die originale Fehlermeldung mit durchreichen, wo hoffentlich ne Zeile oder sonstiger Kontext drinsteht, damit der Benutzer wenigstens ne halbe Chance hat, seinen Tippfehler zu finden.

2018-03-01 08:34 UTC, wosc approved these changes
![asked? answered.](https://media.giphy.com/media/3ohhwuzTxy3eQK10Yw/giphy.gif)

2018-03-01 08:34 UTC, merged