TMS-231: Use centrally cached queries to populate all areas within a center page.
ZeitOnline/zeit.content.cp pull request #35
Opened 2018-05-30 12:37 UTC by witsch

See [TMS-231](https://zeit-online.atlassian.net/browse/TMS-231).

2018-06-05 07:50 UTC, wosc requested changes

2018-06-05 07:50 UTC, wosc commented on src/zeit/content/cp/automatic.py
> +        rows = cp.total_teaser_count() + 5      # total teasers + some spares
Das scheint mir als Heuristik etwas zu grob. Wenn wir uns schon zum Sonderfall "es geht um die gleiche TMS-Topicpage" herablassen, sollten wir denke ich dann auch nur die Areas berücksichtigen, die automatic_type=topicpage und referenced_topicpage=self.referenced_topicpage haben. Insofern würd ich eher `cp._cached_areas` irgendwie public machen und dann hier benutzen, anstatt auf der CP `total_teaser_count` einzuführen.

Und... da du unten eh hast "hol so lang welche nach bis es genug sind", kann man die magischen +5 doch auch sein lassen, oder was für einen 80%-Fall stellst du dir da vor?

2018-06-05 07:50 UTC, wosc commented on src/zeit/content/cp/automatic.py
> +        key = (self.topicpage, self.filter_id, self.start)
Noice. :)

2018-06-05 07:50 UTC, wosc commented on src/zeit/content/cp/automatic.py
> +            _, hits = iself._get_documents(start=self.start, rows=0)
`iself`? Du vim-User, du.

2018-06-05 07:50 UTC, wosc commented on src/zeit/content/cp/automatic.py
> +            response, hits = self._get_documents(start=start, rows=rows)
Statt `(response, hits)` gibts `zeit.cms.interfaces.Result`, in der Hoffnung dass es ein bisschen weniger tupelig zu lesen+schreiben ist.

2018-06-05 07:50 UTC, wosc commented on src/zeit/content/cp/automatic.py
> +                start = start + rows            # fetch next batch
Ahaaa. _Das_ ist der eigentliche Fix für das TMS-Dublettenproblem, nicht wahr. Dass man die TMS-Results außerdem noch cached ist mehr so die (campus-)cherry on top, oder?

Und jetzt wo ich das so sehe, erinner ich mich auch: [wir hatten sowas schonmal](https://github.com/ZeitOnline/zeit.content.cp/commit/2c7e5f2ce327a3910cd480d6c79212b53f93b9b6), wenn auch nicht so schön klar aufgeschrieben wie du jetzt.

2018-06-05 12:21 UTC, witsch commented on src/zeit/content/cp/automatic.py
> +        rows = cp.total_teaser_count() + 5      # total teasers + some spares
Ja, da hast du Recht, daß es natürlich auch noch andere areas gibt und wir nur die zählen könnten, die hier relevant sind.  Da hatte ich tatsächlich (nur) das Campus Beispiel im Kopf, wo's halt nur diese gab, also mehr oder weniger... 🙂  Und dann hat der Helper auf der centerpage nichts zu suchen.  Das ist jedenfalls in c3deecee2470440989c4a9143ef58b8236d37be7 & 44760828190840c495409f49af1dd3792c79291c gefixt...

Und ja, der "80%-Fall", den ich mir tatsächlich vorgestellt hab, ist das explizite "anpinnen" von ein paar (wenigen) Artikeln.  Wobei die ja dann in der aktuellen Version eigentlich auch schon mitgezählt würden, oder?

2018-06-05 13:37 UTC, witsch commented on src/zeit/content/cp/automatic.py
> +            _, hits = iself._get_documents(start=self.start, rows=0)
Hihi, offensichtlich wurde `total_hits` (wie vermutet) immer erst nach den Areas aufgerufen :smile: — bzw. gab es überall mindestens eine.  Ist aber mit 6c490e26eb1c4a2250123b9c816beb2af8bfc568 gefixt & getestet...

2018-06-05 13:40 UTC, witsch commented on src/zeit/content/cp/automatic.py
> +            response, hits = self._get_documents(start=start, rows=rows)
Naja, das Problem hier ist ja, daß ich 'nen Iterator haben will, und — hatte ich vorher allerdings auch noch nicht probiert — kann ich keine extra Attribute setzen:
```
~/Z/f/w/s/zeit.content.cp (TMS-231|✚1) $ python
Python 2.7.15 (default, May  1 2018, 16:44:08) 
[GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> i = iter([])
>>> i.hits = 9
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'listiterator' object has only read-only attributes (assign to .hits)
```
:cry:

2018-06-05 13:43 UTC, witsch commented on src/zeit/content/cp/automatic.py
> +                start = start + rows            # fetch next batch
Genau, der Iterator eben.  Und wirklich gecached sind die ja eigentlich nicht, nur eben die (iterierbaren) Resultatlisten zentral gespeichert.  Und dann noch vorher einmal halbwegs "schlau" raten (also zählen :innocent:), um nicht unnötig oft Nachschlag holen zu müssen...

2018-06-05 14:31 UTC, witsch commented on src/zeit/content/cp/automatic.py
> +                start = start + rows            # fetch next batch
Also okay, die Resultate quasi nicht, die Resultatquellen natürlich schon...  immer diese pedantischen Neukollegen, ne!? :joy:

2018-06-07 21:54 UTC, witsch commented
Hmm, also ich glaube ich könnte noch ne Weile weiter putzen, aber nachdem der Kernpunkt ja erledigt und auch der Code imho etwas lesbarer ist, hör ich jetzt mal auf.  Die Cache-Strategien können wir ja ein andermal weiter verfolgen... 🙂

2018-06-08 09:31 UTC, wosc approved these changes
![excellent](https://media.giphy.com/media/uL2GwdqRPoqnS/giphy.gif)

Ich hab an ein paar Namen noch etwas rumgeschraubt (vmtl brauchte ich das für mein persönliches Verständnis...), ich hoffe du bist mir nicht böse.

2018-06-08 09:33 UTC, merged